In [2]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes there is a difference in the data type of variables list_ and array_list

In [3]:
type(array_list)

numpy.ndarray

In [4]:
type(list_)

list

In [5]:
array_list.dtype

dtype('<U1')

## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [38]:
for i in array_list:
    print (i, type(array_list))

1 <class 'numpy.ndarray'>
2 <class 'numpy.ndarray'>
3 <class 'numpy.ndarray'>
4 <class 'numpy.ndarray'>
5 <class 'numpy.ndarray'>


In [39]:
for i in list_:
    print (i,type(list_))

1 <class 'list'>
2 <class 'list'>
3 <class 'list'>
4 <class 'list'>
5 <class 'list'>


## Q3. Considering the following changes in the variable, array_list:array_list = np.array(object = list_, dtype = int)

## Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? 

## If so then print the data types of each and every element present in both the variables, list_and arra_list.

## Consider the below code to answer further questions:

## import numpy as np
## num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
## num_array = np.array(object = num_list)

Yes. There will be any difference in the data type of the elements present in both the variables, list_ and arra_list


In [8]:
array_list = np.array(object = list_, dtype = int)

In [9]:
array_list

array([1, 2, 3, 4, 5])

In [11]:
type(list_)

list

In [12]:
type(array_list)

numpy.ndarray

## Q4. Write a code to find the following characteristics of variable, num_array:
## (i) shape
## (ii) size

In [13]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [14]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
num_array.shape

(2, 3)

In [16]:
num_array.size

6

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
## [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [23]:
x= np.zeros([3  ,3])
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
print(x.shape)
print(x.size)


(3, 3)
9


## Q6. Create an identity matrix of shape (5,5) using numpy functions?
## [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [30]:
l =[1,1,1,1,1]

In [32]:
x2 = np.diag(l)
x2

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [33]:
print(x2.size)
print(x2.shape)

25
(5, 5)
